import { View, Text, StyleSheet, ScrollView } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { shareContent, generateAndSharePDF } from '../../utils/sharing';
import { Card } from '../../components/Card';
import { Button } from '../../components/Button';
import { ProgressBar } from '../../components/ProgressBar';
import { theme } from '../../constants/theme';
import { useLocalSearchParams } from 'expo-router';


export default function ReportScreen() {
  const { id } = useLocalSearchParams();

  return (
    <SafeAreaView style={styles.container}>
      <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.scrollContent}>
        <View style={styles.header}>
          <Text style={styles.title}>Verification Report</Text>
          <Text style={styles.subtitle}>Search ID: {id}</Text>
        </View>

        <Card style={styles.statusCard}>
          <View style={styles.statusContent}>
            <View style={styles.statusBadge}>
              <MaterialCommunityIcons name="clock-outline" size={24} color={theme.text} />
            </View>
            <View>
              <Text style={styles.statusTitle}>Verification Pending</Text>
              <Text style={styles.statusDesc}>We're currently reviewing this business</Text>
            </View>
          </View>
        </Card>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Progress</Text>
          <Card>
            <ProgressBar progress={35} label="Overall Progress" />
            <View style={styles.timelineInfo}>
              <Text style={styles.timelineLabel}>Estimated completion:</Text>
              <Text style={styles.timelineValue}>5-7 business days</Text>
            </View>
          </Card>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Verification Stages</Text>
          <Card>
            {[
              { done: true, label: 'Submitted', desc: 'Your verification request has been received' },
              { done: true, label: 'Document Review', desc: 'We are reviewing your documents' },
              { done: false, label: 'Address Verification', desc: 'Pending' },
              { done: false, label: 'Field Visit', desc: 'Scheduled' },
              { done: false, label: 'Final Report', desc: 'Coming soon' },
            ].map((stage, idx) => (
              <View key={idx} style={styles.stageItem}>
                <View
                  style={[
                    styles.stageDot,
                    stage.done && styles.stageDotDone,
                  ]}
                >
                  {stage.done && <MaterialCommunityIcons name="check" size={12} color={theme.white} />}
                </View>
                <View style={styles.stageContent}>
                  <Text style={styles.stageLabel}>{stage.label}</Text>
                  <Text style={styles.stageDesc}>{stage.desc}</Text>
                </View>
              </View>
            ))}
          </Card>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Report Info</Text>
          <Card>
            <View style={styles.infoItem}>
              <Text style={styles.infoLabel}>Report ID</Text>
              <Text style={styles.infoValue}>{id}</Text>
            </View>
            <View style={styles.infoItem}>
              <Text style={styles.infoLabel}>Submitted</Text>
              <Text style={styles.infoValue}>Today</Text>
            </View>
            <View style={styles.infoItem}>
              <Text style={styles.infoLabel}>Status</Text>
              <Text style={[styles.infoValue, styles.pendingStatus]}>In Progress</Text>
            </View>
          </Card>
        </View>

        <View style={styles.actions}>
          <Button
            title="Share Report"
            onPress={() => shareContent(`Verification Report for ID: ${id}. Status: In Progress. Check Authentify for details.`)}
            variant="outline"
            size="md"
            fullWidth
            icon={<MaterialCommunityIcons name="share-variant" size={18} color={theme.primary} />}
          />
          <Button
            title="Download as PDF"
            onPress={() => {
              const html = `
                    <h1>Verification Report</h1>
                    <h2>ID: ${id}</h2>
                    <p>Status: <strong>In Progress</strong></p>
                    <p>Generated by Authentify</p>
                `;
              generateAndSharePDF(html);
            }}
            variant="secondary"
            size="md"
            fullWidth
            icon={<MaterialCommunityIcons name="file-pdf-box" size={18} color={theme.white} />}
          />
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.surface,
  },
  scrollContent: {
    paddingHorizontal: theme.spacing.lg,
    paddingTop: theme.spacing.md,
    paddingBottom: theme.spacing.xl,
  },
  header: {
    marginBottom: theme.spacing.xl,
  },
  title: {
    fontSize: 24,
    fontWeight: '800',
    color: theme.text,
    marginBottom: theme.spacing.sm,
  },
  subtitle: {
    fontSize: 13,
    color: theme.textSecondary,
  },
  statusCard: {
    marginBottom: theme.spacing.xl,
    backgroundColor: '#FFFBF0',
  },
  statusContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing.md,
  },
  statusBadge: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: theme.warning,
    justifyContent: 'center',
    alignItems: 'center',
  },
  statusBadgeText: {
    fontSize: 24,
  },
  statusTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: theme.text,
  },
  statusDesc: {
    fontSize: 12,
    color: theme.textSecondary,
    marginTop: 2,
  },
  section: {
    marginBottom: theme.spacing.xl,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: theme.text,
    marginBottom: theme.spacing.md,
  },
  timelineInfo: {
    marginTop: theme.spacing.lg,
    paddingTop: theme.spacing.lg,
    borderTopWidth: 1,
    borderTopColor: theme.border,
  },
  timelineLabel: {
    fontSize: 12,
    color: theme.textSecondary,
    fontWeight: '600',
  },
  timelineValue: {
    fontSize: 14,
    fontWeight: '700',
    color: theme.warning,
    marginTop: theme.spacing.sm,
  },
  stageItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: theme.spacing.md,
    paddingVertical: theme.spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: theme.border,
  },
  stageDot: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: theme.border,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 2,
  },
  stageDotDone: {
    backgroundColor: theme.secondary,
    borderColor: theme.secondary,
  },
  checkmark: {
    color: theme.white,
    fontWeight: '700',
    fontSize: 12,
  },
  stageContent: {
    flex: 1,
  },
  stageLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: theme.text,
  },
  stageDesc: {
    fontSize: 11,
    color: theme.textSecondary,
    marginTop: 2,
  },
  infoItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: theme.spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: theme.border,
  },
  infoLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: theme.textSecondary,
  },
  infoValue: {
    fontSize: 13,
    fontWeight: '700',
    color: theme.text,
  },
  pendingStatus: {
    color: theme.warning,
  },
  actions: {
    gap: theme.spacing.md,
  },
});
